language: csharp
solution: DnD_NPC_Creator/DnD_NPC_Creator.sln
mono: none
dotnet: 3.0
before_script: cd DnD_NPC_Creator/
script:
    - dotnet restore
    - dotnet build
    - dotnet test DnD_NPC_Creator/Business_Layer.UnitTests/Business_Layer.UnitTests.csproj
