//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data_Layer {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource1 {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource1() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Data_Layer.Resource1", typeof(Resource1).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Acolyte.
        /// </summary>
        internal static string comboBox_background_Item {
            get {
                return ResourceManager.GetString("comboBox_background.Item", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Charlatan.
        /// </summary>
        internal static string comboBox_background_Item1 {
            get {
                return ResourceManager.GetString("comboBox_background.Item1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sailor.
        /// </summary>
        internal static string comboBox_background_Item10 {
            get {
                return ResourceManager.GetString("comboBox_background.Item10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Soldier.
        /// </summary>
        internal static string comboBox_background_Item11 {
            get {
                return ResourceManager.GetString("comboBox_background.Item11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Urchin.
        /// </summary>
        internal static string comboBox_background_Item12 {
            get {
                return ResourceManager.GetString("comboBox_background.Item12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Criminal.
        /// </summary>
        internal static string comboBox_background_Item2 {
            get {
                return ResourceManager.GetString("comboBox_background.Item2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entertainer.
        /// </summary>
        internal static string comboBox_background_Item3 {
            get {
                return ResourceManager.GetString("comboBox_background.Item3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Folk Hero.
        /// </summary>
        internal static string comboBox_background_Item4 {
            get {
                return ResourceManager.GetString("comboBox_background.Item4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guild Artisan.
        /// </summary>
        internal static string comboBox_background_Item5 {
            get {
                return ResourceManager.GetString("comboBox_background.Item5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hermit.
        /// </summary>
        internal static string comboBox_background_Item6 {
            get {
                return ResourceManager.GetString("comboBox_background.Item6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Noble.
        /// </summary>
        internal static string comboBox_background_Item7 {
            get {
                return ResourceManager.GetString("comboBox_background.Item7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Outlander.
        /// </summary>
        internal static string comboBox_background_Item8 {
            get {
                return ResourceManager.GetString("comboBox_background.Item8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sage.
        /// </summary>
        internal static string comboBox_background_Item9 {
            get {
                return ResourceManager.GetString("comboBox_background.Item9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Barbarian.
        /// </summary>
        internal static string comboBox_class_Item {
            get {
                return ResourceManager.GetString("comboBox_class.Item", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bard.
        /// </summary>
        internal static string comboBox_class_Item1 {
            get {
                return ResourceManager.GetString("comboBox_class.Item1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warlock.
        /// </summary>
        internal static string comboBox_class_Item10 {
            get {
                return ResourceManager.GetString("comboBox_class.Item10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wizard.
        /// </summary>
        internal static string comboBox_class_Item11 {
            get {
                return ResourceManager.GetString("comboBox_class.Item11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ceric.
        /// </summary>
        internal static string comboBox_class_Item2 {
            get {
                return ResourceManager.GetString("comboBox_class.Item2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Druid.
        /// </summary>
        internal static string comboBox_class_Item3 {
            get {
                return ResourceManager.GetString("comboBox_class.Item3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fighter.
        /// </summary>
        internal static string comboBox_class_Item4 {
            get {
                return ResourceManager.GetString("comboBox_class.Item4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monk.
        /// </summary>
        internal static string comboBox_class_Item5 {
            get {
                return ResourceManager.GetString("comboBox_class.Item5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paladin.
        /// </summary>
        internal static string comboBox_class_Item6 {
            get {
                return ResourceManager.GetString("comboBox_class.Item6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ranger.
        /// </summary>
        internal static string comboBox_class_Item7 {
            get {
                return ResourceManager.GetString("comboBox_class.Item7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rogue.
        /// </summary>
        internal static string comboBox_class_Item8 {
            get {
                return ResourceManager.GetString("comboBox_class.Item8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorcorer.
        /// </summary>
        internal static string comboBox_class_Item9 {
            get {
                return ResourceManager.GetString("comboBox_class.Item9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dwarf.
        /// </summary>
        internal static string comboBox_race_Item {
            get {
                return ResourceManager.GetString("comboBox_race.Item", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Elf.
        /// </summary>
        internal static string comboBox_race_Item1 {
            get {
                return ResourceManager.GetString("comboBox_race.Item1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Halfling.
        /// </summary>
        internal static string comboBox_race_Item2 {
            get {
                return ResourceManager.GetString("comboBox_race.Item2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Human.
        /// </summary>
        internal static string comboBox_race_Item3 {
            get {
                return ResourceManager.GetString("comboBox_race.Item3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dragonborn.
        /// </summary>
        internal static string comboBox_race_Item4 {
            get {
                return ResourceManager.GetString("comboBox_race.Item4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gnome.
        /// </summary>
        internal static string comboBox_race_Item5 {
            get {
                return ResourceManager.GetString("comboBox_race.Item5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Half-Elf.
        /// </summary>
        internal static string comboBox_race_Item6 {
            get {
                return ResourceManager.GetString("comboBox_race.Item6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Half-Orc.
        /// </summary>
        internal static string comboBox_race_Item7 {
            get {
                return ResourceManager.GetString("comboBox_race.Item7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tiefling.
        /// </summary>
        internal static string comboBox_race_Item8 {
            get {
                return ResourceManager.GetString("comboBox_race.Item8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I cheat at games of chance..
        /// </summary>
        internal static string comboBox_specialization_Item {
            get {
                return ResourceManager.GetString("comboBox_specialization.Item", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I shave coins or forge documents..
        /// </summary>
        internal static string comboBox_specialization_Item1 {
            get {
                return ResourceManager.GetString("comboBox_specialization.Item1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Highway robber.
        /// </summary>
        internal static string comboBox_specialization_Item10 {
            get {
                return ResourceManager.GetString("comboBox_specialization.Item10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hired killer.
        /// </summary>
        internal static string comboBox_specialization_Item11 {
            get {
                return ResourceManager.GetString("comboBox_specialization.Item11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pickpocket.
        /// </summary>
        internal static string comboBox_specialization_Item12 {
            get {
                return ResourceManager.GetString("comboBox_specialization.Item12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Smuggler.
        /// </summary>
        internal static string comboBox_specialization_Item13 {
            get {
                return ResourceManager.GetString("comboBox_specialization.Item13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actor.
        /// </summary>
        internal static string comboBox_specialization_Item14 {
            get {
                return ResourceManager.GetString("comboBox_specialization.Item14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dancer.
        /// </summary>
        internal static string comboBox_specialization_Item15 {
            get {
                return ResourceManager.GetString("comboBox_specialization.Item15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fire-eater.
        /// </summary>
        internal static string comboBox_specialization_Item16 {
            get {
                return ResourceManager.GetString("comboBox_specialization.Item16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jester.
        /// </summary>
        internal static string comboBox_specialization_Item17 {
            get {
                return ResourceManager.GetString("comboBox_specialization.Item17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Juggler.
        /// </summary>
        internal static string comboBox_specialization_Item18 {
            get {
                return ResourceManager.GetString("comboBox_specialization.Item18", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Instrumentalist.
        /// </summary>
        internal static string comboBox_specialization_Item19 {
            get {
                return ResourceManager.GetString("comboBox_specialization.Item19", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I insinuate myself into people&apos;s lives to prey on their
        ///weakness and secure their fortunes..
        /// </summary>
        internal static string comboBox_specialization_Item2 {
            get {
                return ResourceManager.GetString("comboBox_specialization.Item2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Poet.
        /// </summary>
        internal static string comboBox_specialization_Item20 {
            get {
                return ResourceManager.GetString("comboBox_specialization.Item20", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Singer.
        /// </summary>
        internal static string comboBox_specialization_Item21 {
            get {
                return ResourceManager.GetString("comboBox_specialization.Item21", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Storyteller.
        /// </summary>
        internal static string comboBox_specialization_Item22 {
            get {
                return ResourceManager.GetString("comboBox_specialization.Item22", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tumbler.
        /// </summary>
        internal static string comboBox_specialization_Item23 {
            get {
                return ResourceManager.GetString("comboBox_specialization.Item23", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I stood up to a tyrant&apos;s agents..
        /// </summary>
        internal static string comboBox_specialization_Item24 {
            get {
                return ResourceManager.GetString("comboBox_specialization.Item24", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I saved people during a natural disaster..
        /// </summary>
        internal static string comboBox_specialization_Item25 {
            get {
                return ResourceManager.GetString("comboBox_specialization.Item25", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I stood alone against a terrible monster..
        /// </summary>
        internal static string comboBox_specialization_Item26 {
            get {
                return ResourceManager.GetString("comboBox_specialization.Item26", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I stole from a corrupt merchant to help the poor..
        /// </summary>
        internal static string comboBox_specialization_Item27 {
            get {
                return ResourceManager.GetString("comboBox_specialization.Item27", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I led a militia to fight off an invading army..
        /// </summary>
        internal static string comboBox_specialization_Item28 {
            get {
                return ResourceManager.GetString("comboBox_specialization.Item28", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I broke into a tyrant&apos;s castle and stole weapons to arm
        ///the people..
        /// </summary>
        internal static string comboBox_specialization_Item29 {
            get {
                return ResourceManager.GetString("comboBox_specialization.Item29", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I put on new identities like clothes..
        /// </summary>
        internal static string comboBox_specialization_Item3 {
            get {
                return ResourceManager.GetString("comboBox_specialization.Item3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I trained the peasantry to use farm implements as
        ///weapons against a tyrant&apos;s soldiers..
        /// </summary>
        internal static string comboBox_specialization_Item30 {
            get {
                return ResourceManager.GetString("comboBox_specialization.Item30", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A lord rescinded an unpopular decree after I led a
        ///symbolic act of protect against it..
        /// </summary>
        internal static string comboBox_specialization_Item31 {
            get {
                return ResourceManager.GetString("comboBox_specialization.Item31", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A celestial, fey, or similar creature gave me a blessing
        ///or revealed my secret origin..
        /// </summary>
        internal static string comboBox_specialization_Item32 {
            get {
                return ResourceManager.GetString("comboBox_specialization.Item32", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recruited into a lord&apos;s army, I rose to leadership and
        ///was commended for my heroism..
        /// </summary>
        internal static string comboBox_specialization_Item33 {
            get {
                return ResourceManager.GetString("comboBox_specialization.Item33", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alchemists and apothecaries.
        /// </summary>
        internal static string comboBox_specialization_Item34 {
            get {
                return ResourceManager.GetString("comboBox_specialization.Item34", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Armorers, locksmiths, and finesmiths.
        /// </summary>
        internal static string comboBox_specialization_Item35 {
            get {
                return ResourceManager.GetString("comboBox_specialization.Item35", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brewers, distillers, and vintners.
        /// </summary>
        internal static string comboBox_specialization_Item36 {
            get {
                return ResourceManager.GetString("comboBox_specialization.Item36", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calligraphers, scribes, and scriveners.
        /// </summary>
        internal static string comboBox_specialization_Item37 {
            get {
                return ResourceManager.GetString("comboBox_specialization.Item37", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Carpenters, roofers, and plasterers.
        /// </summary>
        internal static string comboBox_specialization_Item38 {
            get {
                return ResourceManager.GetString("comboBox_specialization.Item38", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cartographers, surveyors, and chart-makers.
        /// </summary>
        internal static string comboBox_specialization_Item39 {
            get {
                return ResourceManager.GetString("comboBox_specialization.Item39", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I run sleight-of-hand cons on street corners..
        /// </summary>
        internal static string comboBox_specialization_Item4 {
            get {
                return ResourceManager.GetString("comboBox_specialization.Item4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cobblers and shoemakers.
        /// </summary>
        internal static string comboBox_specialization_Item40 {
            get {
                return ResourceManager.GetString("comboBox_specialization.Item40", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cooks and bakers.
        /// </summary>
        internal static string comboBox_specialization_Item41 {
            get {
                return ResourceManager.GetString("comboBox_specialization.Item41", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Glassblowers and glaziers.
        /// </summary>
        internal static string comboBox_specialization_Item42 {
            get {
                return ResourceManager.GetString("comboBox_specialization.Item42", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jewelers and gemcutters.
        /// </summary>
        internal static string comboBox_specialization_Item43 {
            get {
                return ResourceManager.GetString("comboBox_specialization.Item43", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leatherworkers, skinners, and tanners.
        /// </summary>
        internal static string comboBox_specialization_Item44 {
            get {
                return ResourceManager.GetString("comboBox_specialization.Item44", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Masons and stonecutters.
        /// </summary>
        internal static string comboBox_specialization_Item45 {
            get {
                return ResourceManager.GetString("comboBox_specialization.Item45", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Painters, Iimners, and sign-makers.
        /// </summary>
        internal static string comboBox_specialization_Item46 {
            get {
                return ResourceManager.GetString("comboBox_specialization.Item46", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Potters and tile-makers.
        /// </summary>
        internal static string comboBox_specialization_Item47 {
            get {
                return ResourceManager.GetString("comboBox_specialization.Item47", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shipwrights and sailmakers.
        /// </summary>
        internal static string comboBox_specialization_Item48 {
            get {
                return ResourceManager.GetString("comboBox_specialization.Item48", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Smiths and metal-forgers.
        /// </summary>
        internal static string comboBox_specialization_Item49 {
            get {
                return ResourceManager.GetString("comboBox_specialization.Item49", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I convince people that worthless junk is worth their
        ///hard-earned money..
        /// </summary>
        internal static string comboBox_specialization_Item5 {
            get {
                return ResourceManager.GetString("comboBox_specialization.Item5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tinkers, pewterers, and casters.
        /// </summary>
        internal static string comboBox_specialization_Item50 {
            get {
                return ResourceManager.GetString("comboBox_specialization.Item50", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wagon-makers and wheelwrights.
        /// </summary>
        internal static string comboBox_specialization_Item51 {
            get {
                return ResourceManager.GetString("comboBox_specialization.Item51", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weavers and dyers.
        /// </summary>
        internal static string comboBox_specialization_Item52 {
            get {
                return ResourceManager.GetString("comboBox_specialization.Item52", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Woodcarvers, coopers, and bowyers.
        /// </summary>
        internal static string comboBox_specialization_Item53 {
            get {
                return ResourceManager.GetString("comboBox_specialization.Item53", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I was searching for spiritual enlightenment..
        /// </summary>
        internal static string comboBox_specialization_Item54 {
            get {
                return ResourceManager.GetString("comboBox_specialization.Item54", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I was partaking of communal living in accordance with
        ///the dictates of a religious order..
        /// </summary>
        internal static string comboBox_specialization_Item55 {
            get {
                return ResourceManager.GetString("comboBox_specialization.Item55", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I was exiled for a crime I didn&apos;t commit..
        /// </summary>
        internal static string comboBox_specialization_Item56 {
            get {
                return ResourceManager.GetString("comboBox_specialization.Item56", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I retreated from society after a life-altering event..
        /// </summary>
        internal static string comboBox_specialization_Item57 {
            get {
                return ResourceManager.GetString("comboBox_specialization.Item57", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I needed a quiet place to work on my art, literature,
        ///music, or manifesto..
        /// </summary>
        internal static string comboBox_specialization_Item58 {
            get {
                return ResourceManager.GetString("comboBox_specialization.Item58", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I needed to commune with nature, far from civilization..
        /// </summary>
        internal static string comboBox_specialization_Item59 {
            get {
                return ResourceManager.GetString("comboBox_specialization.Item59", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blackmailer.
        /// </summary>
        internal static string comboBox_specialization_Item6 {
            get {
                return ResourceManager.GetString("comboBox_specialization.Item6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I was the caretaker of an ancient ruin or relic..
        /// </summary>
        internal static string comboBox_specialization_Item60 {
            get {
                return ResourceManager.GetString("comboBox_specialization.Item60", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I was a pilgrim in search of a person, place, or relic of
        ///spiritual significance..
        /// </summary>
        internal static string comboBox_specialization_Item61 {
            get {
                return ResourceManager.GetString("comboBox_specialization.Item61", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forester.
        /// </summary>
        internal static string comboBox_specialization_Item62 {
            get {
                return ResourceManager.GetString("comboBox_specialization.Item62", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trapper.
        /// </summary>
        internal static string comboBox_specialization_Item63 {
            get {
                return ResourceManager.GetString("comboBox_specialization.Item63", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Homesteader.
        /// </summary>
        internal static string comboBox_specialization_Item64 {
            get {
                return ResourceManager.GetString("comboBox_specialization.Item64", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guide.
        /// </summary>
        internal static string comboBox_specialization_Item65 {
            get {
                return ResourceManager.GetString("comboBox_specialization.Item65", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exile or outcast.
        /// </summary>
        internal static string comboBox_specialization_Item66 {
            get {
                return ResourceManager.GetString("comboBox_specialization.Item66", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bounty hunter.
        /// </summary>
        internal static string comboBox_specialization_Item67 {
            get {
                return ResourceManager.GetString("comboBox_specialization.Item67", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pilgrim.
        /// </summary>
        internal static string comboBox_specialization_Item68 {
            get {
                return ResourceManager.GetString("comboBox_specialization.Item68", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tribal nomad.
        /// </summary>
        internal static string comboBox_specialization_Item69 {
            get {
                return ResourceManager.GetString("comboBox_specialization.Item69", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Burglar.
        /// </summary>
        internal static string comboBox_specialization_Item7 {
            get {
                return ResourceManager.GetString("comboBox_specialization.Item7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hunter-gatherer.
        /// </summary>
        internal static string comboBox_specialization_Item70 {
            get {
                return ResourceManager.GetString("comboBox_specialization.Item70", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tribal marauder.
        /// </summary>
        internal static string comboBox_specialization_Item71 {
            get {
                return ResourceManager.GetString("comboBox_specialization.Item71", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alchemist.
        /// </summary>
        internal static string comboBox_specialization_Item72 {
            get {
                return ResourceManager.GetString("comboBox_specialization.Item72", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Astronomer.
        /// </summary>
        internal static string comboBox_specialization_Item73 {
            get {
                return ResourceManager.GetString("comboBox_specialization.Item73", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discredited academic.
        /// </summary>
        internal static string comboBox_specialization_Item74 {
            get {
                return ResourceManager.GetString("comboBox_specialization.Item74", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to librarian.
        /// </summary>
        internal static string comboBox_specialization_Item75 {
            get {
                return ResourceManager.GetString("comboBox_specialization.Item75", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Professor.
        /// </summary>
        internal static string comboBox_specialization_Item76 {
            get {
                return ResourceManager.GetString("comboBox_specialization.Item76", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Researcher.
        /// </summary>
        internal static string comboBox_specialization_Item77 {
            get {
                return ResourceManager.GetString("comboBox_specialization.Item77", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wizard&apos;s apprentice.
        /// </summary>
        internal static string comboBox_specialization_Item78 {
            get {
                return ResourceManager.GetString("comboBox_specialization.Item78", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scribe.
        /// </summary>
        internal static string comboBox_specialization_Item79 {
            get {
                return ResourceManager.GetString("comboBox_specialization.Item79", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enforcer.
        /// </summary>
        internal static string comboBox_specialization_Item8 {
            get {
                return ResourceManager.GetString("comboBox_specialization.Item8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Officer.
        /// </summary>
        internal static string comboBox_specialization_Item80 {
            get {
                return ResourceManager.GetString("comboBox_specialization.Item80", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scout.
        /// </summary>
        internal static string comboBox_specialization_Item81 {
            get {
                return ResourceManager.GetString("comboBox_specialization.Item81", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Infantry.
        /// </summary>
        internal static string comboBox_specialization_Item82 {
            get {
                return ResourceManager.GetString("comboBox_specialization.Item82", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calvary.
        /// </summary>
        internal static string comboBox_specialization_Item83 {
            get {
                return ResourceManager.GetString("comboBox_specialization.Item83", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Healer.
        /// </summary>
        internal static string comboBox_specialization_Item84 {
            get {
                return ResourceManager.GetString("comboBox_specialization.Item84", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quartermaster.
        /// </summary>
        internal static string comboBox_specialization_Item85 {
            get {
                return ResourceManager.GetString("comboBox_specialization.Item85", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Standard bearer.
        /// </summary>
        internal static string comboBox_specialization_Item86 {
            get {
                return ResourceManager.GetString("comboBox_specialization.Item86", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Support staff (cook, blacksmith, or the like).
        /// </summary>
        internal static string comboBox_specialization_Item87 {
            get {
                return ResourceManager.GetString("comboBox_specialization.Item87", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fence.
        /// </summary>
        internal static string comboBox_specialization_Item9 {
            get {
                return ResourceManager.GetString("comboBox_specialization.Item9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hill Dwarf.
        /// </summary>
        internal static string comboBox_subrace_Item {
            get {
                return ResourceManager.GetString("comboBox_subrace.Item", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mountain Dwarf.
        /// </summary>
        internal static string comboBox_subrace_Item1 {
            get {
                return ResourceManager.GetString("comboBox_subrace.Item1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Illuskan.
        /// </summary>
        internal static string comboBox_subrace_Item10 {
            get {
                return ResourceManager.GetString("comboBox_subrace.Item10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mulan.
        /// </summary>
        internal static string comboBox_subrace_Item11 {
            get {
                return ResourceManager.GetString("comboBox_subrace.Item11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rashemi.
        /// </summary>
        internal static string comboBox_subrace_Item12 {
            get {
                return ResourceManager.GetString("comboBox_subrace.Item12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shou.
        /// </summary>
        internal static string comboBox_subrace_Item13 {
            get {
                return ResourceManager.GetString("comboBox_subrace.Item13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tethyrian.
        /// </summary>
        internal static string comboBox_subrace_Item14 {
            get {
                return ResourceManager.GetString("comboBox_subrace.Item14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Turami.
        /// </summary>
        internal static string comboBox_subrace_Item15 {
            get {
                return ResourceManager.GetString("comboBox_subrace.Item15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forest Gnome.
        /// </summary>
        internal static string comboBox_subrace_Item16 {
            get {
                return ResourceManager.GetString("comboBox_subrace.Item16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rock Gnome.
        /// </summary>
        internal static string comboBox_subrace_Item17 {
            get {
                return ResourceManager.GetString("comboBox_subrace.Item17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to High Elf.
        /// </summary>
        internal static string comboBox_subrace_Item2 {
            get {
                return ResourceManager.GetString("comboBox_subrace.Item2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wood Elf.
        /// </summary>
        internal static string comboBox_subrace_Item3 {
            get {
                return ResourceManager.GetString("comboBox_subrace.Item3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dark Elf.
        /// </summary>
        internal static string comboBox_subrace_Item4 {
            get {
                return ResourceManager.GetString("comboBox_subrace.Item4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lightfoot.
        /// </summary>
        internal static string comboBox_subrace_Item5 {
            get {
                return ResourceManager.GetString("comboBox_subrace.Item5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stout.
        /// </summary>
        internal static string comboBox_subrace_Item6 {
            get {
                return ResourceManager.GetString("comboBox_subrace.Item6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calishite.
        /// </summary>
        internal static string comboBox_subrace_Item7 {
            get {
                return ResourceManager.GetString("comboBox_subrace.Item7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chondathan.
        /// </summary>
        internal static string comboBox_subrace_Item8 {
            get {
                return ResourceManager.GetString("comboBox_subrace.Item8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Damaran.
        /// </summary>
        internal static string comboBox_subrace_Item9 {
            get {
                return ResourceManager.GetString("comboBox_subrace.Item9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Charisma.
        /// </summary>
        internal static string label_charisma_Text {
            get {
                return ResourceManager.GetString("label_charisma.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Class.
        /// </summary>
        internal static string label_class_Text {
            get {
                return ResourceManager.GetString("label_class.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Constitution.
        /// </summary>
        internal static string label_constitution_Text {
            get {
                return ResourceManager.GetString("label_constitution.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dexterity.
        /// </summary>
        internal static string label_dexterity_Text {
            get {
                return ResourceManager.GetString("label_dexterity.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Intelligence.
        /// </summary>
        internal static string label_intelligence_Text {
            get {
                return ResourceManager.GetString("label_intelligence.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string label_name_Text {
            get {
                return ResourceManager.GetString("label_name.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Race.
        /// </summary>
        internal static string label_race_Text {
            get {
                return ResourceManager.GetString("label_race.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Strength.
        /// </summary>
        internal static string label_strength_Text {
            get {
                return ResourceManager.GetString("label_strength.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subrace.
        /// </summary>
        internal static string label_subrace_Text {
            get {
                return ResourceManager.GetString("label_subrace.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wisdom.
        /// </summary>
        internal static string label_wisdom_Text {
            get {
                return ResourceManager.GetString("label_wisdom.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string textBox_charisma_Text {
            get {
                return ResourceManager.GetString("textBox_charisma.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string textBox_classDescription_ {
            get {
                return ResourceManager.GetString("textBox_classDescription_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A tall human tribesman strides through a blizzard,draped in fur and hefting his axe. He laughs as he
        ///charges toward the frost giant who dared poach his
        ///people&apos;s elk herdo
        ///A half-orc snarls at the latest challenger to her
        ///authority over their savage tribe, ready to break his neck
        ///with her bare hands as she did to the last six rivaIs.
        ///Frothing at the mouth, a dwarf slams his helmet into
        ///the face of his drow foe, then turns to drive his armored
        ///elbow into the gut of another.
        ///
        ///These barbarians, differ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string textBox_classDescription_barbarian_Text {
            get {
                return ResourceManager.GetString("textBox_classDescription_barbarian.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Humming as she traces her fingers over an ancient monument in a long-forgotten ruin, a half-elf in rugged leathers finds knowledge springing into her mind, conjured forth by the magic of her song — knowledge of the people who constructed the monument and the mythic saga it depicts.
        ///
        ///A stern human warrior bangs his sword rhythmically against his scale mail, setting the tempo for his war chant and exhorting his companions to bravery and heroism. The magic of his song fortifies and emboldens them.
        ///
        ///Laughin [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string textBox_classDescription_bard_Text {
            get {
                return ResourceManager.GetString("textBox_classDescription_bard.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arms and eyes upraised toward the sun and a prayer on his lips, an elf begins to glow with an inner light that spills out to heal his battle-worn companions.
        ///
        ///Chanting a song of glory, a dwarf swings his axe in wide swaths to cut through the ranks of orcs arrayed against him, shouting praise to the gods with every foe’s fall.
        ///
        ///Calling down a curse upon the forces of undeath, a human lifts her holy symbol as light pours from it to drive back the zombies crowding in on her companions.
        ///
        ///Clerics are inter [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string textBox_classDescription_cleric_Text {
            get {
                return ResourceManager.GetString("textBox_classDescription_cleric.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Holding high a gnarled staff wreathed with holly, an elf summons the fury of the storm and calls down explosive bolts of lightning to smite the torch-carrying orcs who threaten her forest.
        ///
        ///Crouching out of sight on a high tree branch in the form of a leopard, a human peers out of the jungle at the strange construction of a temple of Evil Elemental Air, keeping a close eye on the cultists’ activities.
        ///
        ///Swinging a blade formed of pure fire, a half-elf charges into a mass of skeletal soldiers, sundering t [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string textBox_classDescription_druid_Text {
            get {
                return ResourceManager.GetString("textBox_classDescription_druid.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A human in clanging plate armor holds her shield before her as she runs toward the massed goblins. An elf behind her, clad in studded leather armor, peppers the goblins with arrows loosed from his exquisite bow. The half-orc nearby shouts orders, helping the two combatants coordinate their assault to the best advantage.
        ///
        ///A dwarf in chain mail interposes his shield between the ogre’s club and his companion, knocking the deadly blow aside. His companion, a half-elf in scale armor, swings two scimitars in a  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string textBox_classDescription_fighter_Text {
            get {
                return ResourceManager.GetString("textBox_classDescription_fighter.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Her fists a blur as they deflect an incoming hail of arrows, a half-elf springs over a barricade and throws herself into the massed ranks of hobgoblins on the other side. She whirls among them, knocking their blows aside and sending them reeling, until at last she stands alone.
        ///
        ///Taking a deep breath, a human covered in tattoos settles into a battle stance. As the first charging orcs reach him, he exhales and a blast of fire roars from his mouth, engulfing his foes.
        ///
        ///Moving with the silence of the night, [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string textBox_classDescription_monk_Text {
            get {
                return ResourceManager.GetString("textBox_classDescription_monk.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clad in plate armor that gleams in the sunlight despite the dust and grime of long travel, a human lays down her sword and shield and places her hands on a mortally wounded man. Divine radiance shines from her hands, the man’s wounds knit closed, and his eyes open wide with amazement.
        ///
        ///A dwarf crouches behind an outcrop, his black cloak making him nearly invisible in the night, and watches an orc war band celebrating its recent victory. Silently, he stalks into their midst and whispers an oath, and two or [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string textBox_classDescription_paladin_Text {
            get {
                return ResourceManager.GetString("textBox_classDescription_paladin.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rough and wild looking, a human stalks alone through the shadows of trees, hunting the orcs he knows are planning a raid on a nearby farm. Clutching a shortsword in each hand, he becomes a whirlwind of steel, cutting down one enemy after another.
        ///
        ///After tumbling away from a cone of freezing air, an elf finds her feet and draws back her bow to loose an arrow at the white dragon. Shrugging off the wave of fear that emanates from the dragon like the cold of its breath, she sends one arrow after another to fi [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string textBox_classDescription_ranger_Text {
            get {
                return ResourceManager.GetString("textBox_classDescription_ranger.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Signaling for her companions to wait, a halfling creeps forward through the dungeon hall. She presses an ear to the door, then pulls out a set of tools and picks the lock in the blink of an eye. Then she disappears into the shadows as her fighter friend moves forward to kick the door open.
        ///
        ///A human lurks in the shadows of an alley while his accomplice prepares for her part in the ambush. When their target — a notorious slaver — passes the alleyway, the accomplice cries out, the slaver comes to investigate [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string textBox_classDescription_rogue_Text {
            get {
                return ResourceManager.GetString("textBox_classDescription_rogue.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Golden eyes flashing, a human stretches out her hand and unleashes the dragonfire that burns in her veins. As an inferno rages around her foes, leathery wings spread from her back and she takes to the air.
        ///
        ///Long hair whipped by a conjured wind, a half-elf spreads his arms wide and throws his head back. Lifting him momentarily off the ground, a wave of magic surges up in him, through him, and out from him in a mighty blast of lightning.
        ///
        ///Crouching behind a stalagmite, a halfling points a finger at a char [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string textBox_classDescription_sorcorer_Text {
            get {
                return ResourceManager.GetString("textBox_classDescription_sorcorer.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to With a pseudodragon curled on his shoulder, a young elf in golden robes smiles warmly, weaving a magical charm into his honeyed words and bending the palace sentinel to his will.
        ///
        ///As flames spring to life in her hands, a wizened human whispers the secret name of her demonic patron, infusing her spell with fiendish magic.
        ///
        ///Shifting his gaze between a battered tome and the odd alignment of the stars overhead, a wild-eyed tiefling chants the mystic ritual that will open a doorway to a distant world.
        ///
        ///War [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string textBox_classDescription_warlock_Text {
            get {
                return ResourceManager.GetString("textBox_classDescription_warlock.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clad in the silver robes that denote her station, an elf closes her eyes to shut out the distractions of the battlefield and begins her quiet chant. Fingers weaving in front of her, she completes her spell and launches a tiny bead of fire toward the enemy ranks, where it erupts into a conflagration that engulfs the soldiers.
        ///
        ///Checking and rechecking his work, a human scribes an intricate magic circle in chalk on the bare stone floor, then sprinkles powdered iron along every line and graceful curve. When t [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string textBox_classDescription_wizard_Text {
            get {
                return ResourceManager.GetString("textBox_classDescription_wizard.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string textBox_constitution_Text {
            get {
                return ResourceManager.GetString("textBox_constitution.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string textBox_dexterity_Text {
            get {
                return ResourceManager.GetString("textBox_dexterity.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string textBox_intelligence_Text {
            get {
                return ResourceManager.GetString("textBox_intelligence.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string textBox_name_Text {
            get {
                return ResourceManager.GetString("textBox_name.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Born of dragons, as their name proclaims, the
        ///dragonborn walk proudly through a world that greets
        ///them with fearful incomprehension. Shaped by draconic
        ///gods or the dragons themselves, dragonborn originally
        ///hatched from dragon eggs as a unique race, combining
        ///the best attributes of dragons and humanoids. Some
        ///dragonborn are faithful servants to true dragons, others
        ///form the ranks of soldiers in great wars, and still others
        ///find themselves adrift, with no clear calling in life..
        /// </summary>
        internal static string textBox_raceDescription_dragonborn_Text {
            get {
                return ResourceManager.GetString("textBox_raceDescription_dragonborn.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kingdoms rich in ancient grandeur, halls carved into the
        ///roots of mountains, the echoing of picks and hammers
        ///in deep mines and blazing forges, a commitment to
        ///clan and tradition, and a burning hatred of goblins and
        ///orcs-these common threads unite all dwarves..
        /// </summary>
        internal static string textBox_raceDescription_dwarf_Text {
            get {
                return ResourceManager.GetString("textBox_raceDescription_dwarf.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Elves are a magical people of otherworldly grace, living
        ///in the world but not entirely part of it. They live in
        ///places of ethereal beauty, in the midst of ancient forests
        ///or in silvery spires glittering with faerie light, where
        ///soft music drifts through the air and gentle fragrances
        ///waft on the breeze. Elves love nature and magic, art
        ///and artistry, music and poetry, and the good things
        ///of the world..
        /// </summary>
        internal static string textBox_raceDescription_elf_Text {
            get {
                return ResourceManager.GetString("textBox_raceDescription_elf.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A constant hum of busy activity pervades the warrens
        ///and neighborhoods where gnomes form their closeknit
        ///communities. Louder sounds punctuate the hum:
        ///a crunch of grinding gears here, a minor explosion
        ///there, a yelp of surprise or triumph, and especially
        ///bursts of laughter. Gnomes take delight in life, enjoying
        ///every moment of invention, exploration, investigation,
        ///creation, and play..
        /// </summary>
        internal static string textBox_raceDescription_gnome_Text {
            get {
                return ResourceManager.GetString("textBox_raceDescription_gnome.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Walking in two worlds but truly belonging to neither,
        ///half-elves combine what some say are the best qualities
        ///of their elf and human parents: human curiosity,
        ///inventiveness, and ambition tempered by the refined
        ///senses, love of nature, and artistic tastes of the elves.
        ///Some half-elves Iive among humans, set apart by their
        ///emotional and physical differences, watching friends
        ///and loved ones age while time barely touches them.
        ///Others Iive with the elves, growing restless as they
        ///reach adulthood in the  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string textBox_raceDescription_halfElf_Text {
            get {
                return ResourceManager.GetString("textBox_raceDescription_halfElf.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The comforts of home are the goals of most halflings&apos;
        ///lives: a place to settle in peace and quiet, far from
        ///marauding monsters and clashing armies; a blazing fire
        ///and a generous meal; fine drink and fine conversation.
        ///Though some halflings live out their days in remote
        ///agricultural communities, others form nomadic bands
        ///that travel constantly, lured by the open road and the
        ///wide horizon to discover the wonders of new lands and
        ///peoples. But even these wanderers love peace, food,
        ///hearth, and home, th [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string textBox_raceDescription_halfling_Text {
            get {
                return ResourceManager.GetString("textBox_raceDescription_halfling.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Whether united under the leadership of a mighty
        ///warlock or having fought to a standstill after years
        ///of conflict, orc and human tribes sometimes form
        ///alliances, joining forces into a larger horde to the terror
        ///of civilized lands nearby. When these alliances are
        ///sealed by marriages, half-orcs are born. Some half-ores
        ///rise to become proud chiefs of orc tribes, their human
        ///blood giving them an edge over their full-blooded orc
        ///rivaIs. Some venture into the world to prove their worth
        ///among humans and ot [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string textBox_raceDescription_halfOrc_Text {
            get {
                return ResourceManager.GetString("textBox_raceDescription_halfOrc.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In the reckonings of most worlds. humans are the
        ///youngest of the common races, late to arrive on the
        ///world scene and short-lived in comparison to dwarves.
        ///elves, and dragons. Perhaps it is because of their shorter
        ///lives that they strive to achieve as much as they can in
        ///the years they are given. Or maybe they feel they have
        ///something to prove to the elder races. and that&apos;s why
        ///they build their mighty empires on the foundation of
        ///conquest and trade. Whatever drives them, humans
        ///are the innovators, t [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string textBox_raceDescription_human_Text {
            get {
                return ResourceManager.GetString("textBox_raceDescription_human.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To be greeted with stares and whispers, to suffer
        ///violence and insult on the street, to see mistrust and
        ///fear in every eye: this is the lot of the tiefling. And to
        ///twist the knife, tieflings know that this is because a
        ///pact struck generations ago infused the essence of
        ///Asmodeus-overlord of the Nine Hells-into their
        ///bloodline. Their appearance and their nature are not
        ///their fault but the result of an ancient sin, for which
        ///they and their children and their children&apos;s children
        ///will always be held acc [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string textBox_raceDescription_tiefling_Text {
            get {
                return ResourceManager.GetString("textBox_raceDescription_tiefling.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string textBox_strength_Text {
            get {
                return ResourceManager.GetString("textBox_strength.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shorter and slighter in build than most other humans,
        ///Calishites have dusky brown skin, hair, and eyes.
        ///They&apos;re found primarily in southwest Faerûn..
        /// </summary>
        internal static string textBox_subraceDescription_calishite_Text {
            get {
                return ResourceManager.GetString("textBox_subraceDescription_calishite.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chondathans are slender, tawny-skinned folk with
        ///brown hair that ranges from almost blond to almost
        ///black. Most are tall and have green or brown eyes,
        ///but these trails are hardly universal. Humans of
        ///Chondalhan descent dominate the centrallands of
        ///Faerûn, around the Inner Sea..
        /// </summary>
        internal static string textBox_subraceDescription_chondathan_Text {
            get {
                return ResourceManager.GetString("textBox_subraceDescription_chondathan.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Found primarily in the northwest of Faerûn, Damarans
        ///are of moderate height and build, with skin hues
        ///ranging from tawny to fair. Their hair is usually brown
        ///or black, and their eye color varies widely, though brown
        ///is most common..
        /// </summary>
        internal static string textBox_subraceDescription_damaran_Text {
            get {
                return ResourceManager.GetString("textBox_subraceDescription_damaran.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Descended from an earlier subrace of dark-skinned
        ///elves, the drow were banished from the surface world
        ///for following the goddess Lolth down the path to
        ///evil and corruption. Now they have built their own
        ///civilizalion in the depths of the Underdark, patterned
        ///after the Way of Lolth. Also called dark elves, the drow
        ///have black skin that resembles polished obsidian and
        ///stark white or pale yellow hair. They commonly have
        ///very pale eyes (so pale as to be mistaken for white) in
        ///shades of lilac, silver, pi [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string textBox_subraceDescription_darkElf_Text {
            get {
                return ResourceManager.GetString("textBox_subraceDescription_darkElf.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to As a forest gnome, you have a natural knack for iIlusion
        ///and inherent quickness and stealth. In the worlds of
        ///D&amp;D, forest gnomes are rare and secretive. They gather
        ///in hidden communities in sylvan forests, using iIlusions
        ///and trickery to conceal themselves from threats or
        ///to mask their escape should they be detected. Forest
        ///gnomes tend to be friendly with other good-spirited
        ///woodland folk, and they regard elves and good fey as
        ///their most important allies. These gnomes also befriend
        ///small forest ani [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string textBox_subraceDescription_forestGnome_Text {
            get {
                return ResourceManager.GetString("textBox_subraceDescription_forestGnome.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to As a high elf, you have a keep mind and a mastery of
        ///at least the basics of magic. In many of the worlds
        ///of D&amp;D, there are two kinds of high elves. One type
        ///(which includes the gray elves and valley elves of
        ///Greyhawk, the Silvanesti of Dragonlance, and the
        ///sun elves of the Forgotten Realms) is haughty and
        ///reclusive, believing themselves to be superior to
        ///non-elves and even other elves. The other type
        ///(including the high elves of Greyhawk. the
        ///Qualinesti of Dragonlance, and the moon elves
        ///of the Fo [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string textBox_subraceDescription_highElf_Text {
            get {
                return ResourceManager.GetString("textBox_subraceDescription_highElf.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to As a hill dwarf, you have keen senses, deep intuition,
        ///and remarkable resilience. The gold dwarves of Faenûn
        ///in their mighty southern kingdom are hill dwarves, as
        ///are the exiled Neidar and the debased Klar of Krynn in
        ///the Oragonlance setting..
        /// </summary>
        internal static string textBox_subraceDescription_hillDwarf_Text {
            get {
                return ResourceManager.GetString("textBox_subraceDescription_hillDwarf.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IIluskans are tall, fair-skinned folk with blue or steely
        ///gray eyes. Most have raven-black hair, but those who
        ///inhabit the extreme northwest have blond, red, or
        ///light brown hair..
        /// </summary>
        internal static string textBox_subraceDescription_illuskan_Text {
            get {
                return ResourceManager.GetString("textBox_subraceDescription_illuskan.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to As a lightfoot halfling, you can easily hide from notice,
        ///even using other people as cover. You&apos;re inclined to be
        ///affable and get along well with others. In the Forgotten
        ///Realms, lightfoot halflings have spread the farthest and
        ///thus are the most common variety.
        ///Lightfoots are more prone to wanderlust than other
        ///halflings. and often dwell alongside other races or take
        ///up a nomadic life. In the world of Greyhawk. these
        ///halflings are called hairfeet or tallfellows..
        /// </summary>
        internal static string textBox_subraceDescription_lightfoot_Text {
            get {
                return ResourceManager.GetString("textBox_subraceDescription_lightfoot.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to As a mountain dwarf, you&apos;re strong and hardy,
        ///accustomed to a difficult life in rugged terrain. You&apos;re
        ///probably on the tall side (for a dwarf), and tend toward
        ///lighter coloration, The shield dwarves of northern
        ///Faerûn, as well as the ruling Hylar clan and the noble
        ///Oaewar clan of Oragonlance, are mountain dwarves..
        /// </summary>
        internal static string textBox_subraceDescription_mountainDwarf_Text {
            get {
                return ResourceManager.GetString("textBox_subraceDescription_mountainDwarf.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dominant in the eastern and southeastern shores of
        ///the lnner Sea, the Mulan are generally tall, slim, and
        ///amber-skinned, with eyes of hazel or brown. Their hair
        ///ranges from black to dark brown, but in the lands where
        ///the Mulan are most prominent, nobles and many other
        ///Mulan shave off all their hair..
        /// </summary>
        internal static string textBox_subraceDescription_mulan_Text {
            get {
                return ResourceManager.GetString("textBox_subraceDescription_mulan.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Most often found east of the Inner Sea and often
        ///intermingled with the Mulan, Rashemis tend to be short,
        ///stout, and muscular. They usually have dusky skin, dark
        ///eyes, and thick black hair..
        /// </summary>
        internal static string textBox_subraceDescription_rashemi_Text {
            get {
                return ResourceManager.GetString("textBox_subraceDescription_rashemi.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to As a rock gnome, you have a natural inventiveness and
        ///hardiness beyond that of other gnomes. Most gnomes
        ///in the worlds of D&amp;D are rock gnomes, including the
        ///tinker gnomes of the Dragonlance setting..
        /// </summary>
        internal static string textBox_subraceDescription_rockGnome_Text {
            get {
                return ResourceManager.GetString("textBox_subraceDescription_rockGnome.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Shou are the most numerous and powerful ethnic
        ///group in Kara-Tur, far to the east of Faerûn. They are
        ///yellowish-bronze in hue, with black hair and dark
        ///eyes. Shou surnames are usually presented before
        ///the given name..
        /// </summary>
        internal static string textBox_subraceDescription_shou_Text {
            get {
                return ResourceManager.GetString("textBox_subraceDescription_shou.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to As a stout halfling. you&apos;re hardier than average and have
        ///some resistance to poison. Some say that stouts have
        ///dwarven blood. In the Forgotten Realms, these halflings
        ///are called stronghearts. and they&apos;re most common
        ///in the south..
        /// </summary>
        internal static string textBox_subraceDescription_stout_Text {
            get {
                return ResourceManager.GetString("textBox_subraceDescription_stout.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Widespread along the entire Sword Coast at the
        ///western edge of Faerûn, Tethyrians are of medium build
        ///and height, with dusky skin that tends to grow fairer
        ///the farther north they dwell. Their hair and eye color
        ///varies widely, but brown hair and blue eyes are the most
        ///common. Tethyrians primarily use Chondathan names..
        /// </summary>
        internal static string textBox_subraceDescription_tethyrian_Text {
            get {
                return ResourceManager.GetString("textBox_subraceDescription_tethyrian.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Native to the southern shore of the Inner Sea, the
        ///Turami people are generally tall and muscular, with
        ///dark mahogany skin, curly black hair, and dark eyes..
        /// </summary>
        internal static string textBox_subraceDescription_turami_Text {
            get {
                return ResourceManager.GetString("textBox_subraceDescription_turami.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to As a wood elf, you have keen senses and intuition, and
        ///your fleet feet carry you quickly and stealthily through
        ///your nalive forests. This category includes the wild
        ///elves (grugach) of Greyhawk and lhe Kagonesti of
        ///Dragonlance, as well as the races called wood elves in
        ///Greyhawk and the Forgotten Realms. In Faenûn, wood
        ///elves (also called wild elves, green elves, or forest elves)
        ///are reclusive and distrusting of non-elves.
        ///Wood elves&apos; skin lends to be copperish in hue,
        ///sometimes with traces of green. [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string textBox_subraceDescription_woodElf_Text {
            get {
                return ResourceManager.GetString("textBox_subraceDescription_woodElf.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string textBox_wisdom_Text {
            get {
                return ResourceManager.GetString("textBox_wisdom.Text", resourceCulture);
            }
        }
    }
}
