//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data_Layer {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource1 {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource1() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Data_Layer.Resource1", typeof(Resource1).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Barbarian.
        /// </summary>
        internal static string comboBox_class_Barbarian {
            get {
                return ResourceManager.GetString("comboBox_class.Barbarian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cleric.
        /// </summary>
        internal static string comboBox_class_Cleric {
            get {
                return ResourceManager.GetString("comboBox_class.Cleric", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Druid.
        /// </summary>
        internal static string comboBox_class_Druid {
            get {
                return ResourceManager.GetString("comboBox_class.Druid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fighter.
        /// </summary>
        internal static string comboBox_class_Fighter {
            get {
                return ResourceManager.GetString("comboBox_class.Fighter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hunter.
        /// </summary>
        internal static string comboBox_class_Hunter {
            get {
                return ResourceManager.GetString("comboBox_class.Hunter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monk.
        /// </summary>
        internal static string comboBox_class_Monk {
            get {
                return ResourceManager.GetString("comboBox_class.Monk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paladin.
        /// </summary>
        internal static string comboBox_class_Paladin {
            get {
                return ResourceManager.GetString("comboBox_class.Paladin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorcorer.
        /// </summary>
        internal static string comboBox_class_Sorcorer {
            get {
                return ResourceManager.GetString("comboBox_class.Sorcorer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warlock.
        /// </summary>
        internal static string comboBox_class_Warlock {
            get {
                return ResourceManager.GetString("comboBox_class.Warlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wizard.
        /// </summary>
        internal static string comboBox_class_Wizard {
            get {
                return ResourceManager.GetString("comboBox_class.Wizard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dragonborn.
        /// </summary>
        internal static string comboBox_race_Dragonborn {
            get {
                return ResourceManager.GetString("comboBox_race.Dragonborn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dwarf.
        /// </summary>
        internal static string comboBox_race_Dwarf {
            get {
                return ResourceManager.GetString("comboBox_race.Dwarf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Elf.
        /// </summary>
        internal static string comboBox_race_Elf {
            get {
                return ResourceManager.GetString("comboBox_race.Elf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gnome.
        /// </summary>
        internal static string comboBox_race_Gnome {
            get {
                return ResourceManager.GetString("comboBox_race.Gnome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Half-Elf.
        /// </summary>
        internal static string comboBox_race_HalfElf {
            get {
                return ResourceManager.GetString("comboBox_race.HalfElf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Halfling.
        /// </summary>
        internal static string comboBox_race_Halfling {
            get {
                return ResourceManager.GetString("comboBox_race.Halfling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Half-Orc.
        /// </summary>
        internal static string comboBox_race_HalfOrc {
            get {
                return ResourceManager.GetString("comboBox_race.HalfOrc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Human.
        /// </summary>
        internal static string comboBox_race_Human {
            get {
                return ResourceManager.GetString("comboBox_race.Human", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tiefling.
        /// </summary>
        internal static string comboBox_race_Tiefling {
            get {
                return ResourceManager.GetString("comboBox_race.Tiefling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calishite.
        /// </summary>
        internal static string comboBox_subrace_Calishite {
            get {
                return ResourceManager.GetString("comboBox_subrace.Calishite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chondathan.
        /// </summary>
        internal static string comboBox_subrace_Chondathan {
            get {
                return ResourceManager.GetString("comboBox_subrace.Chondathan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Damaran.
        /// </summary>
        internal static string comboBox_subrace_Damaran {
            get {
                return ResourceManager.GetString("comboBox_subrace.Damaran", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dark Elf.
        /// </summary>
        internal static string comboBox_subrace_DarkElf {
            get {
                return ResourceManager.GetString("comboBox_subrace.DarkElf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forest Gnome.
        /// </summary>
        internal static string comboBox_subrace_ForestGnome {
            get {
                return ResourceManager.GetString("comboBox_subrace.ForestGnome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to High Elf.
        /// </summary>
        internal static string comboBox_subrace_HighElf {
            get {
                return ResourceManager.GetString("comboBox_subrace.HighElf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hill Dwarf.
        /// </summary>
        internal static string comboBox_subrace_HillDwarf {
            get {
                return ResourceManager.GetString("comboBox_subrace.HillDwarf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Illuskan.
        /// </summary>
        internal static string comboBox_subrace_Illuskan {
            get {
                return ResourceManager.GetString("comboBox_subrace.Illuskan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lightfoot.
        /// </summary>
        internal static string comboBox_subrace_Lightfoot {
            get {
                return ResourceManager.GetString("comboBox_subrace.Lightfoot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mountain Dwarf.
        /// </summary>
        internal static string comboBox_subrace_MountainDwarf {
            get {
                return ResourceManager.GetString("comboBox_subrace.MountainDwarf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mulan.
        /// </summary>
        internal static string comboBox_subrace_Mulan {
            get {
                return ResourceManager.GetString("comboBox_subrace.Mulan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rashemi.
        /// </summary>
        internal static string comboBox_subrace_Rashemi {
            get {
                return ResourceManager.GetString("comboBox_subrace.Rashemi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rock Gnome.
        /// </summary>
        internal static string comboBox_subrace_RockGnome {
            get {
                return ResourceManager.GetString("comboBox_subrace.RockGnome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shou.
        /// </summary>
        internal static string comboBox_subrace_Shou {
            get {
                return ResourceManager.GetString("comboBox_subrace.Shou", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stout.
        /// </summary>
        internal static string comboBox_subrace_Stout {
            get {
                return ResourceManager.GetString("comboBox_subrace.Stout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tethyrian.
        /// </summary>
        internal static string comboBox_subrace_Tethyrian {
            get {
                return ResourceManager.GetString("comboBox_subrace.Tethyrian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Turami.
        /// </summary>
        internal static string comboBox_subrace_Turami {
            get {
                return ResourceManager.GetString("comboBox_subrace.Turami", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wood Elf.
        /// </summary>
        internal static string comboBox_subrace_WoodElf {
            get {
                return ResourceManager.GetString("comboBox_subrace.WoodElf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Charisma.
        /// </summary>
        internal static string label_charisma_Text {
            get {
                return ResourceManager.GetString("label_charisma.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Class.
        /// </summary>
        internal static string label_class_Text {
            get {
                return ResourceManager.GetString("label_class.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Constitution.
        /// </summary>
        internal static string label_constitution_Text {
            get {
                return ResourceManager.GetString("label_constitution.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dexterity.
        /// </summary>
        internal static string label_dexterity_Text {
            get {
                return ResourceManager.GetString("label_dexterity.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Intelligence.
        /// </summary>
        internal static string label_intelligence_Text {
            get {
                return ResourceManager.GetString("label_intelligence.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string label_name_Text {
            get {
                return ResourceManager.GetString("label_name.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Race.
        /// </summary>
        internal static string label_race_Text {
            get {
                return ResourceManager.GetString("label_race.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Strength.
        /// </summary>
        internal static string label_strength_Text {
            get {
                return ResourceManager.GetString("label_strength.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subrace.
        /// </summary>
        internal static string label_subrace_Text {
            get {
                return ResourceManager.GetString("label_subrace.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wisdom.
        /// </summary>
        internal static string label_wisdom_Text {
            get {
                return ResourceManager.GetString("label_wisdom.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string textBox_charisma_Text {
            get {
                return ResourceManager.GetString("textBox_charisma.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string textBox_constitution_Text {
            get {
                return ResourceManager.GetString("textBox_constitution.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string textBox_dexterity_Text {
            get {
                return ResourceManager.GetString("textBox_dexterity.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string textBox_intelligence_Text {
            get {
                return ResourceManager.GetString("textBox_intelligence.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string textBox_name_Text {
            get {
                return ResourceManager.GetString("textBox_name.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string textBox_strength_Text {
            get {
                return ResourceManager.GetString("textBox_strength.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string textBox_wisdom_Text {
            get {
                return ResourceManager.GetString("textBox_wisdom.Text", resourceCulture);
            }
        }
    }
}
